# The Engineering World

## Array Shape Manipulation

In [1]:
import numpy as np

### reshape

from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape

NOTE: This will be a new view object if possible; otherwise, it will be a copy.

In [2]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
my_start_array.shape

(24,)

In [5]:
my_3_8_array = my_start_array.reshape((3, 8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [6]:
my_3_8_array[0,0] = 1234

In [7]:
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [8]:
my_ravel_array = my_3_8_array.ravel()

In [9]:
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [10]:
my_ravel_array.shape

(24,)

In [11]:
for n in my_3_8_array.flat:
    print(n)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
