# The Engineering World

## Joining and Splitting Arrays
- concatenate
- stack
- split


In [2]:
import numpy as np

In [3]:
a = np.array([[1,2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6]])

In [5]:
together = np.concatenate((a, b), axis=0)

In [6]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
together.shape

(3, 2)

In [8]:
together[1, 1] = 555

In [9]:
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
c = np.array([[1,2], [3,4]]) *3 + 5

In [12]:
c

array([[ 8, 11],
       [14, 17]])

In [13]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [14]:
arrays = np.zeros((5, 3, 4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[ 1.04073391, -0.63017809, -0.94232819, -0.59783087],
        [ 0.08156964,  0.7847392 , -0.61206902, -1.07297066],
        [-1.41238659,  1.31141483, -0.60622989,  0.11852275]],

       [[-0.98055759, -0.12074175,  0.00863384,  1.64075007],
        [-1.1245683 ,  0.18478822,  1.78380708,  0.51649777],
        [-0.31665234, -2.26345375, -0.13819644,  1.38307989]],

       [[-0.10377109, -1.13388221,  1.08557652, -0.2549433 ],
        [-0.59658705, -2.33728567, -0.11507117, -0.23946759],
        [-2.29871859, -1.1668989 , -0.64951829,  0.14947251]],

       [[ 1.19010318,  1.41816911,  0.91577027, -0.91764817],
        [-0.30916799,  0.98190797, -0.11356874,  1.67582846],
        [ 0.0023462 , -0.81243895,  0.07262913, -0.01420603]],

       [[-0.40073048, -0.53231992,  0.06464473,  0.99647208],
        [ 1.49699781, -0.32289624,  0.29718648, -0.8881659 ],
        [-0.03626886, -0.00563975, -0.60482469, -0.30864424]]])

In [15]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [16]:
stack0

array([[[ 1.04073391, -0.63017809, -0.94232819, -0.59783087],
        [ 0.08156964,  0.7847392 , -0.61206902, -1.07297066],
        [-1.41238659,  1.31141483, -0.60622989,  0.11852275]],

       [[-0.98055759, -0.12074175,  0.00863384,  1.64075007],
        [-1.1245683 ,  0.18478822,  1.78380708,  0.51649777],
        [-0.31665234, -2.26345375, -0.13819644,  1.38307989]],

       [[-0.10377109, -1.13388221,  1.08557652, -0.2549433 ],
        [-0.59658705, -2.33728567, -0.11507117, -0.23946759],
        [-2.29871859, -1.1668989 , -0.64951829,  0.14947251]],

       [[ 1.19010318,  1.41816911,  0.91577027, -0.91764817],
        [-0.30916799,  0.98190797, -0.11356874,  1.67582846],
        [ 0.0023462 , -0.81243895,  0.07262913, -0.01420603]],

       [[-0.40073048, -0.53231992,  0.06464473,  0.99647208],
        [ 1.49699781, -0.32289624,  0.29718648, -0.8881659 ],
        [-0.03626886, -0.00563975, -0.60482469, -0.30864424]]])

In [17]:
stack1

array([[[ 1.04073391, -0.63017809, -0.94232819, -0.59783087],
        [-0.98055759, -0.12074175,  0.00863384,  1.64075007],
        [-0.10377109, -1.13388221,  1.08557652, -0.2549433 ],
        [ 1.19010318,  1.41816911,  0.91577027, -0.91764817],
        [-0.40073048, -0.53231992,  0.06464473,  0.99647208]],

       [[ 0.08156964,  0.7847392 , -0.61206902, -1.07297066],
        [-1.1245683 ,  0.18478822,  1.78380708,  0.51649777],
        [-0.59658705, -2.33728567, -0.11507117, -0.23946759],
        [-0.30916799,  0.98190797, -0.11356874,  1.67582846],
        [ 1.49699781, -0.32289624,  0.29718648, -0.8881659 ]],

       [[-1.41238659,  1.31141483, -0.60622989,  0.11852275],
        [-0.31665234, -2.26345375, -0.13819644,  1.38307989],
        [-2.29871859, -1.1668989 , -0.64951829,  0.14947251],
        [ 0.0023462 , -0.81243895,  0.07262913, -0.01420603],
        [-0.03626886, -0.00563975, -0.60482469, -0.30864424]]])

In [18]:
stack2

array([[[ 1.04073391, -0.98055759, -0.10377109,  1.19010318,
         -0.40073048],
        [-0.63017809, -0.12074175, -1.13388221,  1.41816911,
         -0.53231992],
        [-0.94232819,  0.00863384,  1.08557652,  0.91577027,
          0.06464473],
        [-0.59783087,  1.64075007, -0.2549433 , -0.91764817,
          0.99647208]],

       [[ 0.08156964, -1.1245683 , -0.59658705, -0.30916799,
          1.49699781],
        [ 0.7847392 ,  0.18478822, -2.33728567,  0.98190797,
         -0.32289624],
        [-0.61206902,  1.78380708, -0.11507117, -0.11356874,
          0.29718648],
        [-1.07297066,  0.51649777, -0.23946759,  1.67582846,
         -0.8881659 ]],

       [[-1.41238659, -0.31665234, -2.29871859,  0.0023462 ,
         -0.03626886],
        [ 1.31141483, -2.26345375, -1.1668989 , -0.81243895,
         -0.00563975],
        [-0.60622989, -0.13819644, -0.64951829,  0.07262913,
         -0.60482469],
        [ 0.11852275,  1.38307989,  0.14947251, -0.01420603,
         -0

In [19]:
temp = np.arange(5)
np.split(temp, 1)

[array([0, 1, 2, 3, 4])]

In [20]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [21]:
s0=np.split (before_split, 5, axis = 0)
s0

[array([[[ 1.04073391, -0.63017809, -0.94232819, -0.59783087],
         [ 0.08156964,  0.7847392 , -0.61206902, -1.07297066],
         [-1.41238659,  1.31141483, -0.60622989,  0.11852275]]]),
 array([[[-0.98055759, -0.12074175,  0.00863384,  1.64075007],
         [-1.1245683 ,  0.18478822,  1.78380708,  0.51649777],
         [-0.31665234, -2.26345375, -0.13819644,  1.38307989]]]),
 array([[[-0.10377109, -1.13388221,  1.08557652, -0.2549433 ],
         [-0.59658705, -2.33728567, -0.11507117, -0.23946759],
         [-2.29871859, -1.1668989 , -0.64951829,  0.14947251]]]),
 array([[[ 1.19010318,  1.41816911,  0.91577027, -0.91764817],
         [-0.30916799,  0.98190797, -0.11356874,  1.67582846],
         [ 0.0023462 , -0.81243895,  0.07262913, -0.01420603]]]),
 array([[[-0.40073048, -0.53231992,  0.06464473,  0.99647208],
         [ 1.49699781, -0.32289624,  0.29718648, -0.8881659 ],
         [-0.03626886, -0.00563975, -0.60482469, -0.30864424]]])]

In [22]:
type(s0)

list

In [23]:
s0[1]

array([[[-0.98055759, -0.12074175,  0.00863384,  1.64075007],
        [-1.1245683 ,  0.18478822,  1.78380708,  0.51649777],
        [-0.31665234, -2.26345375, -0.13819644,  1.38307989]]])

In [24]:
s0[1].shape

(1, 3, 4)

In [25]:
s1=np.split (before_split, 3, axis = 1)
s1

[array([[[ 1.04073391, -0.63017809, -0.94232819, -0.59783087]],
 
        [[-0.98055759, -0.12074175,  0.00863384,  1.64075007]],
 
        [[-0.10377109, -1.13388221,  1.08557652, -0.2549433 ]],
 
        [[ 1.19010318,  1.41816911,  0.91577027, -0.91764817]],
 
        [[-0.40073048, -0.53231992,  0.06464473,  0.99647208]]]),
 array([[[ 0.08156964,  0.7847392 , -0.61206902, -1.07297066]],
 
        [[-1.1245683 ,  0.18478822,  1.78380708,  0.51649777]],
 
        [[-0.59658705, -2.33728567, -0.11507117, -0.23946759]],
 
        [[-0.30916799,  0.98190797, -0.11356874,  1.67582846]],
 
        [[ 1.49699781, -0.32289624,  0.29718648, -0.8881659 ]]]),
 array([[[-1.41238659,  1.31141483, -0.60622989,  0.11852275]],
 
        [[-0.31665234, -2.26345375, -0.13819644,  1.38307989]],
 
        [[-2.29871859, -1.1668989 , -0.64951829,  0.14947251]],
 
        [[ 0.0023462 , -0.81243895,  0.07262913, -0.01420603]],
 
        [[-0.03626886, -0.00563975, -0.60482469, -0.30864424]]])]

In [26]:
s2=np.split (before_split, 4, axis = 2)
s2

[array([[[ 1.04073391],
         [ 0.08156964],
         [-1.41238659]],
 
        [[-0.98055759],
         [-1.1245683 ],
         [-0.31665234]],
 
        [[-0.10377109],
         [-0.59658705],
         [-2.29871859]],
 
        [[ 1.19010318],
         [-0.30916799],
         [ 0.0023462 ]],
 
        [[-0.40073048],
         [ 1.49699781],
         [-0.03626886]]]), array([[[-0.63017809],
         [ 0.7847392 ],
         [ 1.31141483]],
 
        [[-0.12074175],
         [ 0.18478822],
         [-2.26345375]],
 
        [[-1.13388221],
         [-2.33728567],
         [-1.1668989 ]],
 
        [[ 1.41816911],
         [ 0.98190797],
         [-0.81243895]],
 
        [[-0.53231992],
         [-0.32289624],
         [-0.00563975]]]), array([[[-0.94232819],
         [-0.61206902],
         [-0.60622989]],
 
        [[ 0.00863384],
         [ 1.78380708],
         [-0.13819644]],
 
        [[ 1.08557652],
         [-0.11507117],
         [-0.64951829]],
 
        [[ 0.91577027],
   