# The Engineering World

## Views and Copies

In [5]:
import numpy as np

In [6]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [7]:
su_casa = mi_casa

### same or Different

In [8]:
# reference equality
mi_casa is su_casa

True

In [9]:
id(mi_casa)

3027090793456

In [10]:
id(su_casa)

3027090793456

In [11]:
#value Equality

mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [12]:
su_casa[4] = 1010

In [13]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [14]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [15]:
tree_house = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [16]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [17]:
id(tree_house)

3027090875056

In [18]:
id(mi_casa)

3027090793456

In [19]:
tree_house[0] = 214

In [20]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [21]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [22]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [23]:
tree_house is mi_casa

False

## View: a shallow copy

In [24]:
farm_house = tree_house.view()
farm_house.shape = (2, 4)

In [25]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [26]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [27]:
tree_house[3] = -111

In [28]:
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

## Deep Copy 

In [29]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [30]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])